### PR TITLE
Issue/676 improve developer experience

### LINKED ISSUE #676: Improve developer experience (DX) by improving documentation/annotation and playing nice with static analysis language servers
# Describe the issue
I have used `canvasapi` and it seems like a great project. I've noticed some DX issues that I'm offering to fix, if you'll let me.
### Demonstration
Consider the following code:
```python
from canvasapi import Canvas

canvas = Canvas('base url', 'access token')
for course in canvas.get_courses(enrollment_status='active'):
    print(course)
```
Method and attribute discoverability are hampered by the type-blindness of `PaginatedList`. Here, it is evident my static analysis language server (pylance) only knows that `Canvas(...).get_courses()` returns a `PaginatedList`... 
image
...but does not know the elements of `PaginatedList` are `canvasapi.course.Course`, as the documentation states.
image
This makes trying to figure out what is possible with `course` a minor nuisance, and requires looking at the documentation.
image
### Suggestions
I do not presume to know how best to fix this issue, but I believe annotating PaginatedList with a `TypeVar` would fix the issue and provide better support for static analysis servers. It would look something like this:
```python
from typing import TypeVar, Iterable

T = TypeVar('T')

class PaginatedList(object):
    def __init__(
        self,
        content_class:T,
        requester,
        request_method,
        first_url,
        extra_attribs=None,
        _root=None,
        _url_override=None,
        **kwargs
    ):
        ...
    
    def __iter__(self) -> Iterator[T]:
        ...
```
It might even be helpful to:
```python
class PaginatedList(Iterable[T]):
    ...
```
An example of this in the wild would be [Tableau Server Client's `Pager`](https://github.com/tableau/server-client-python/blob/master/tableauserverclient/server/pager.py#L23C1-L52C39), which also de-paginates server responses.

## Attribute Blindness
While documentation doesn't appear to have any issues with displaying available methods, it does appear to hide available attributes, which meant I was constantly using `print(vars(...))` to figure out what attributes are available. Take, for example, the documentation for [`File`](https://canvasapi.readthedocs.io/en/stable/file-ref.html), which does not mention the attributes `'category', 'content-type', 'created_at', 'created_at_date', 'display_name', 'filename', 'folder_id', 'hidden', 'hidden_for_user', 'id', 'lock_at', 'locked', 'locked_for_user', 'media_entry_id', 'mime_class', 'modified_at', 'modified_at_date', 'size', 'thumbnail_url', 'unlock_at', 'updated_at', 'updated_at_date', 'upload_status', 'url', 'uuid' ` and ` 'visibility_level'`. It would be great if these were listed!

A static analysis tool also does not see these attributes:
image

The root cause appears to be that the underlying [`CanvasObject`](https://github.com/ucfopen/canvasapi/blob/master/canvasapi/canvas_object.py) appears to be dynamically loading attributes. Having tried to maintain a python REST API wrapper myself, I understand what a pain it is to have to keep object models up to date, so I am sympathetic. However, Python already has a neat pattern for objects with dynamic attributes, though. It's called a `dict`! It supports syntactic sugar that `CanvasObject` does not. It's not a crime to have behavior-based classes, and behavior-based classes are allowed to have attributes, but how are you going to know if you want to `.download()` a `File` if it's not even clear that `File` has a `display_name` or a `filename`?

With 68 contributors and tooling like `pydantic`, `swagger`, and `JSONSchema`, it seems like it should be feasible to keep or even generate actual models of the Canvas API responses.

Take, for example, UVA's Canvas API documentation, which has [example objects](https://canvas.its.virginia.edu/doc/api/files.html) and [defined models](https://canvas.its.virginia.edu/doc/api/assignments.json). Instructure even keeps a model [change log](https://community.canvaslms.com/t5/Canvas-Change-Log/2025-API-and-CLI-Change-Log/ta-p/626858).

Even API clients for massive applications such as Reddit have at least [attribute lists in the documentation](https://github.com/praw-dev/praw/blob/master/praw/models/reddit/comment.py#L24C2-L57C1).

This is me officially volunteering to take a swing at at least a few objects and figure out how to maintain such a thing sustainably.

### PR DESCRIPTION
**Pull request by HandcartCactus**
# Proposed Changes

* Make annotations on PaginatedList that play nicely with static typing analysis

Fixes #676 part 1.
See [this comment](https://github.com/ucfopen/canvasapi/issues/676#issuecomment-2550308392) for screenshots of the result.

### CODE REVIEW

**Comment by HandcartCactus** [comment]
@bennettscience do you have a moment to review this request?

**Comment by bennettscience** [comment]
I should have looked more carefully - your imports need to be sorted alphabetically on line 3, so `isort` failed. 

Follow the contributing guide so you run all the [applicable style checks](https://github.com/ucfopen/canvasapi/blob/develop/.github/CONTRIBUTING.md#running-code-style-checks) before committing again to avoid a build failure.

**Comment by HandcartCactus** [comment]
My apologies. My code is now passing the code-style checks.

**Review by bennettscience — DISMISSED** [review]

**Comment by bennettscience** [comment]
This all looks good to me. Tests ran locally, updated the Authors and Changelog. Just need @jonespm or @Thetwam to approve my changes to merge.

**Review by bennettscience — APPROVED** [review]

**Review by Thetwam — APPROVED** [review]

**Pull request merged**
