### PR TITLE
#114 Implement __len__() for paginated_list

### PR DESCRIPTION
**Pull request by onomou**

### CODE REVIEW

**Comment by onomou** [comment]
Thank you for your feedback! I understand better now how this all is put together. That wall of text is most helpful.

Somehow I missed the `flake8 `error. I'll look for that again.

This was certainly a naïve way of counting, and I see now how it is not efficient for large sets. I'll look into the approach you outlined, grabbing the last page only.

Do you have any examples of a bookmark ID? I'm don't know anything about those yet.
* * *
My silly reason for wanting a `__len__` function is in pySimpleGUI to populate a ListBox, something vaguely like this:

```
import PySimpleGUI as sg
from canvasapi import Canvas
...
courses = canvas.get_courses()
layout = [[sg.Listbox(values=courses)]]
event, values  = sg.Window('Title').Layout(layout).Read()
```
I at least _hoped_ that maybe implementing `__len__` would fix the error that I get, `TypeError: object of type 'PaginatedList' has no len()` and show me the list of my courses.

I can also imagine wanting to know how many students are enrolled in a class, or how many assignments are in a module.

**Comment by jessemcbride** [comment]
Hey @onomou, as a workaround until we implement a more efficient `PaginatedList.__len__` method, you can always just evaluate the PaginatedList as a `list` to be able to use `len` on it:

```
courses = list(canvas.get_courses())

# len(courses) now works
```

**Comment by Thetwam** [comment]
One place the bookmark can be found is with a user's page views.

Here are the `link` headers for a call to `[...]/api/v1/users/self/page_views`, (URL and user_id yanked)

```
<https://[...]/api/v1/users/[...]/page_views?page=first&per_page=100>; rel="current",
<https://[...]/api/v1/users/[...]/page_views?page= bookmark:WyJzaGFyZDoxMTU4IixbIjIwMTktMDMtMDFUMTE6MzI6MzMuOTYwLTA1OjAwIiwiYThkYTg1ZjctMzFjZC00OTUzLTkxY2YtZGI0NDFkMDE0OTgzIl1d&per_page=100>; rel="next",
<https://[...]/api/v1/users/[...]/page_views?page=first&per_page=100>; rel="first"
```

As you can see, the `next` link provides a long bookmark string for the `page` instead of an integer. Also note that there is no `last` link.

Compare that with something like getting all the users in an account:

```
<https://[...]/api/v1/accounts/[...]/users?page=1&per_page=100>; rel="current",
<https://[...]/api/v1/accounts/[...]/users?page=2&per_page=100>; rel="next",
<https://[...]/api/v1/accounts/[...]/users?page=1&per_page=100>; rel="first",
<https://[...]/api/v1/accounts/[...]/users?page=3980&per_page=100>; rel="last"
```

Note the presence of the `last` header and that `page` is an integer.

**Comment by Thetwam** [comment]
Hey @onomou, are you still interested in working on this issue or would you like us to take over development?

**Comment by onomou** [comment]
Hi @Thetwam, I'm still interested. The last couple weeks somehow ran away from me. I'll be happy for any specific pointers in addition to the above, but hopefully will get some time this week to work on it more.

**Comment by Thetwam** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
