### PR TITLE
Added an upload endpoint to the Folder class

### PR DESCRIPTION
**Pull request by elec3647**
Added an upload() method similar to the one that is under Course. I also opened an issue #189

### CODE REVIEW

**Comment by jessemcbride** [comment]
Hey @elec3647, thanks for your contribution.

It looks like your build failed with some flake8 errors. Specifically:
```
canvasapi/folder.py:137:5: E303 too many blank lines (2)
canvasapi/folder.py:156:18: W291 trailing whitespace
canvasapi/folder.py:159:5: E303 too many blank lines (2)
```

You can run flake8 locally by executing `flake8 canvasapi tests`.

Once those are corrected I'll test it out and we'll get it merged in ASAP.

Thanks again!

**Comment by jessemcbride** [comment]
@elec3647 Are you still interested in working on this? We can reassign if you'd like.

If you have any questions we'd be happy to help!

**Comment by elec3647** [comment]
So sorry! I had some computer problems! I'm back online. I'll write a test and flake8 tonight!

**Comment by jessemcbride** [comment]
Hey @elec3647, sorry for the delay in getting back to this.

I'm excited to see that you've added some examples! Could you create a second PR for them so we can review them separately? It might be easier for you to re-branch off of upstream develop and then include the original changes (`folder.py`, `test_folder.py`, and the fixtures) for this PR and then create your second one afterward.

Generally this change looks good, but I'd like to isolate the actual endpoint changes before giving it a final approval. 

Thank you again for your contributions, really excited to get these in!

**Comment by jessemcbride** [comment]
@elec3647, no worries. Glad you're finding the library useful! Feel free to hop in our Slack channel (see the README) if you have any questions.

Looking forward to it :)

**Comment by Thetwam** [comment]
Hey @elec3647,

We're looking to do a release soon and definitely want to get your code for Folder Uploading in.

Since there's a bunch of unrelated work on this branch, I'd like to break just the new upload code off into it's own branch and do a merge. What do you think?

**Comment by Thetwam** [comment]
Closing in favor of #213

**Pull request closed without merging**
